### ISSUE TITLE
0.2.7

### ISSUE THREAD

**Issue by Sabre8073** [Engarak/miiShop_Install#1]
@Engarak  Ok, I initially tried your suggestions of just trying to upgrade first. I attempted this with the older install and it errored out. I then just did a copy and past from the newer zip file overwriting the older files. Upon launching this did not download as with previous versions. So I deleted everything but my .cias and did a clean install. Doing so I was now able to download to the 3ds. Thanks for this but...…...the install did throw out errors, therefore I thought you might want to be aware of this. Also, as a suggestion for future releases, is it possible to have the script to open the localhost automatically once it's done running? It's just a thought for convenience.

Again thx for the hard work and let me know if I can help test in the future.

[MiiShopInstall_5-19-19-11_10_33.log](https://github.com/Engarak/miiShop_Install/files/3195376/MiiShopInstall_5-19-19-11_10_33.log)

[MiiShop_5-19-19-11_11_10.log](https://github.com/Engarak/miiShop_Install/files/3195377/MiiShop_5-19-19-11_11_10.log)

**Comment by Engarak** [comment]
So I'm glad things worked, sorry you had to do the full reset.  As for errors in the installer it looks like things weren't run as administrator, which I thought I caught but apparently not properly.  I did put some checking into the main script to cover if this type of thing happened, so some files will get made if they didn't get installed properly.  I'll re-work how I do this so this should hopefully it will not happen again.  I will keep on working on this and if something comes up I'll not hesitate to reach out.

**Comment by Engarak** [comment]
Closing since things are working, I have a task set in my project board to fix access denied errors you got before.
