### ISSUE TITLE
Powershell execution policy

### ISSUE THREAD

**Issue by Blank517** [Engarak/miiShop_Install#2]
**Error**
```
.\miiShop_Install.ps1 : File C:\Users\Blank517\Desktop\miiShop\miiShop_Install.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
\+ .\miiShop_Install.ps1
\+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```
How to reproduce:
1. Run the exe without administrator priviledges
2. Run the script in a previously opened powershell instance without administrator priviledges

How to fix:
1. Edit your exe manifest from
`<requestedExecutionLevel level="asInvoker"/>`
to
`<requestedExecutionLevel level="requireAdministrator"/>`
2. Run in powershell `Set-ExecutionPolicy Bypass -Scope Process; .\miiShop_Install.ps1` (answer Y or A) or from cmd `PowerShell.exe -ExecutionPolicy Bypass .\miiShop_Install.ps1`

**Comment by Engarak** [comment]
Wow, you're making my life too easy.  I initially didn't add command execution as it was more of a "system setting" but then again I adjust firewall settings so that contradicts the concept, so I'll take a look at the pull you sent and make a call from there.  I greatly appreciate this information either way.

**Comment by Engarak** [comment]
I thought I put in something to prevent this not running from Admin, but I must have missed something.  can you see if this installer update fixes the issue?  If so, I'll make it as an EXE and update the file I have out there.
[miiShop_Install.zip](https://github.com/Engarak/miiShop_Install/files/3239782/miiShop_Install.zip)

**Comment by pixelmultiplo** [comment]
I solved by opening a Powershell manually and input:

` Set-ExecutionPolicy -ExecutionPolicy Unrestricted`

**Comment by Engarak** [comment]
Well, nothing like replying a year late, sorry I didn't follow up on this like I should have.  This will also resolve the issue, and will be the fix i put in going forward.  I have a note to fix this in the next version.

1. Right click on the `start.bat` file and choose edit, this should open it in Notepad
2. Change the line that looks like this `C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe .\miiShop_Install.ps1` to this `C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe –ExecutionPolicy Bypass -File .\miiShop_Install.ps1`
3. Click the X in the upper right hand corner of Notepad, when prompted to save, click yes
4. After the file is saved, now try running `start.bat`
